package org.eddytucubal.dex_db.dominio;

public enum TypeAccount {
    AHORRO, CORRIENTE, PLAZO_FIJO, MONETARIA, INVERSION, CREDITO, HIPOTECARIO,
    PRESTAMO_PERSONAL, TARJETA_DE_CREDITO, DEBITO, CHEQUES, REMESAS, PAGO_SERVICIOS
}
